name: Python application

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    env :
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
      slack_token: ${{secrets.slack_token}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install os uuid re time
        pip install datetime json pandas requests
        pip install azure.storage.blob
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: run
      run: |
        python slackbot_2021.py
