# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:

jobs:
  build:

    runs-on: ubuntu-latest
    env :
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
      slack_token: ${{secrets.slack_token}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install os uuid re time
        pip install datetime json pandas requests
        pip install azure.storage.blob
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: run
      run: |
        python slackbot_2021.py
